---
title: "\\textbf{Supplementary data 3}"
author: "for\\\n\\textit{Assessing systematic changes in measurements across the data collection period:}\\\n\\textit{A simulation study}"
output: 
  pdf_document:
    toc: true
    number_sections: false
    toc_depth: 3
output_file: "results/supplementary_data_3.pdf"
fontsize: 11pt
geometry: top=2cm, bottom=2cm, left=2cm, right=2cm, landscape
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)

## load results
res <- readRDS("results/res.Rds")

## define labels
# algorithm
alg_labels <- c(
  alg_arima = "ARIMA",
  alg_flsa = "FLSA",
  alg_gam = "GAM",
  alg_lowess = "LOWESS",
  alg_moving_avg = "MA",
  alg_pelt = "PELT",
  alg_piecewise_reg = "PR"
)
# from scico palette "batlow"
# sample(scico::scico(7, palette = "batlow"))
alg_col <- c(
  "#D29243",
  "#818231",
  "#FDAC9C",
  "#134D61",
  "#001959",
  "#3B6C55",
  "#F9CCF9"
)

# distribution
dist_labels <- c(
  norm = "Normal",
  lognorm = "Log-normal"
)

# estimand
estimand_labels <- c(
  range = "Range",
  var = "Variance",
  madm = "Mean absolute deviation around the median",
  n_cpts = "Number of change points"
)

# change pattern
pattern_labels <- c(
  nochange = "No change",
  jump = "Jump",
  linear = "Linear",
  quadratic = "Quadratic",
  recurrent = "Recurrent",
  combined = "All patterns combined"
)

## preprocess results
res <- res %>%
  mutate(algorithm = factor(
    algorithm,
    levels = names(alg_labels),
    labels = unname(alg_labels)
  ))

knitr::opts_chunk$set(
  echo = FALSE,
  fig.width = 7,
  fig.height = 5
)
```

```{r, results='asis', message=FALSE, warning=FALSE, fig.width=12, fig.height=7, out.width="100%", dpi=150}
theme_set(
  theme_minimal(base_size = 15) +
    theme(
      plot.margin = unit(c(0, 0, 0, 0), "cm"),
      strip.text = element_text(size = 14),
      axis.text = element_text(size = 12),
      legend.title = element_text(size = 13),
      legend.text = element_text(size = 12)
    )
)

for (dist in unique(res$distribution)) {
  cat("#", unname(dist_labels[dist]), "distribution", "\n\n")

  for (estimand in names(estimand_labels)) {
    cat("## Estimand:", unname(estimand_labels[estimand]), "\n\n")

    # Define names
    est_col <- paste0(estimand, "_est")
    dif_col <- paste0(estimand, "_dif")
    true_col <- estimand
    estimand_label <- unname(estimand_labels[estimand])

    for (pat in names(pattern_labels)) {
      cat("### Systematic change pattern:", unname(pattern_labels[pat]), "\n\n")

      if (pat == "combined") {
        dat <- res %>%
          filter(distribution == dist)
        if (nrow(dat) == 0) next

        # create boxplot
        p1 <- ggplot(dat, aes(
          x = nobs_cat,
          y = .data[[dif_col]],
          color = algorithm
        )) +
          geom_boxplot(
            outlier.shape = 16,
            outlier.size = 0.3,
            linewidth = 0.3
          ) +
          geom_hline(yintercept = 0, linetype = "dashed", color = "darkgray") +
          scale_color_manual(values = alg_col) +
          theme_minimal() +
          labs(
            title = paste0(
              "Boxplot of ",
              tolower(estimand_label),
              " difference over sample size"
            ),
            x = "Sample size category",
            y = paste(estimand_label, "(estimated - true)"),
            color = "Algorithm"
          ) +
          theme(axis.text.x = element_text(angle = 45, hjust = 1))

        # add facet wrap for second plot
        p2 <- p1 + facet_wrap(~snr, labeller = label_both)
      } else {
        dat <- res %>%
          filter(distribution == dist & pattern == pat)
        if (nrow(dat) == 0) next

        true_line <- dat %>%
          group_by(nobs) %>%
          summarise(true_val = first(.data[[true_col]]), .groups = "drop")

        # create loess plot (span=0.75)
        p1 <- ggplot(dat, aes(
          x = nobs,
          y = .data[[est_col]],
          color = algorithm,
          fill = algorithm
        )) +
          geom_smooth(
            method = "loess",
            span = 0.75,
            se = FALSE,
            alpha = 0.2,
            size = 0.5
          ) +
          geom_line(
            data = true_line,
            aes(x = nobs, y = true_val),
            linetype = "dashed",
            color = "black",
            inherit.aes = FALSE,
            linewidth = 0.4
          ) +
          scale_color_manual(values = alg_col) +
          scale_fill_manual(values = alg_col) +
          theme_minimal() +
          labs(
            title = paste0(
              "Estimated ", tolower(estimand_label),
              " over sample size"
            ),
            subtitle = paste0(
              "(Dashed line indicates the true ",
              tolower(estimand_label), ")"
            ),
            x = "Sample size",
            y = paste("Estimated", tolower(estimand_label)),
            color = "Algorithm",
            fill = "Algorithm"
          )

        # create boxplot
        p2 <- ggplot(dat, aes(
          x = nobs_cat,
          y = .data[[dif_col]],
          color = algorithm
        )) +
          geom_boxplot(
            outlier.shape = 16,
            outlier.size = 0.3,
            linewidth = 0.3
          ) +
          geom_hline(yintercept = 0, linetype = "dashed", color = "darkgray") +
          scale_color_manual(values = alg_col) +
          theme_minimal() +
          labs(
            title = paste0(
              "Boxplot of ",
              tolower(estimand_label),
              " difference over sample size"
            ),
            x = "Sample size category",
            y = paste(estimand_label, "(estimated - true)"),
            color = "Algorithm"
          ) +
          theme(axis.text.x = element_text(angle = 45, hjust = 1))

        # add facet wrap
        if (pat == "notrend") {
          # facet by snr
          p1 <- p1 + facet_grid(rows = vars(snr), labeller = label_both)
          p2 <- p2 + facet_grid(rows = vars(snr), labeller = label_both)
        } else {
          # facet by snr & dmaxf
          p1 <- p1 + facet_grid(snr ~ dmaxf, labeller = label_both)
          p2 <- p2 + facet_grid(snr ~ dmaxf, labeller = label_both)
        }
      }

      print(p1)
      cat("\n\n")
      print(p2)
      cat("\n\n")
    }
  }
}
```

